abstract class ServicesStatesCustomer{}
class InitialStateCustomer extends ServicesStatesCustomer{}
class ChangeNavBarCustomer extends ServicesStatesCustomer{}

class CustomerEnabledLoacationSuccess extends ServicesStatesCustomer{}
class CustomerEnabledLoacationError extends ServicesStatesCustomer{}
class GetCustomerLocationSuccess extends ServicesStatesCustomer{}
class ChangeLatLngSuccess extends ServicesStatesCustomer{}
class ChangeLatLngError extends ServicesStatesCustomer{}
class GetAddressSuccess extends ServicesStatesCustomer{}
class GetAddressError extends ServicesStatesCustomer{}
class GetCategoriesCustomerSuccess extends ServicesStatesCustomer{}
class GetCategoriesCustomerError extends ServicesStatesCustomer{}
class GetCategoriesCustomerLoading extends ServicesStatesCustomer{}
class GetMarkersSuccess extends ServicesStatesCustomer{}
class LogOutLoading extends ServicesStatesCustomer{}
class LogOutSuccess extends ServicesStatesCustomer{}
class LogOutError extends ServicesStatesCustomer{}
class gerImageFromGalleryLoading extends ServicesStatesCustomer{}
class gerImageFromGallerySuccess extends ServicesStatesCustomer{}
class gerImageFromGalleryError extends ServicesStatesCustomer{}
class SetUpCustomerSuccess extends ServicesStatesCustomer{}
class SetUpCustomerLoading extends ServicesStatesCustomer{}
class SetUpCustomerError extends ServicesStatesCustomer{}
class getCustomerSuccess extends ServicesStatesCustomer{}
class getCustomerLoading extends ServicesStatesCustomer{}
class getCustomerError extends ServicesStatesCustomer{}
class changeIdSuccess extends ServicesStatesCustomer{}
class getProvidersbelongToCategoryLoading extends ServicesStatesCustomer{}
class getProvidersbelongToCategorySuccess extends ServicesStatesCustomer{}
class getProvidersbelongToCategoryError extends ServicesStatesCustomer{}

