class Autogenerated {
  Provider provider;

  Autogenerated({this.provider});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    provider = json['provider'] != null
            ? new Provider.fromJson(json['provider'])
            : null;
  }

}

class Provider {
  int id;
  String firstName;
  String lastName;
  String email;
  String phone;
  String cityId;
  String regionId;
  String categoryId;
  Null subCategoryId;
  Null lat;
  Null lng;
  Null address;
  String image;
  Null jobTitle;
  Null jobDescription;
  Null gender;
  String active;
  String apiToken;
  Null code;
  String createdAt;
  String updatedAt;
  Null deletedAt;
  String imageurl;
  Null region;
  Null city;
  Null category;
  Null subCategory;


  Provider.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    email = json['email'];
    phone = json['phone'];
    cityId = json['city_id'];
    regionId = json['region_id'];
    categoryId = json['category_id'];
    subCategoryId = json['sub_category_id'];
    lat = json['lat'];
    lng = json['lng'];
    address = json['address'];
    image = json['image'];
    jobTitle = json['job_title'];
    jobDescription = json['job_description'];
    gender = json['gender'];
    active = json['active'];
    apiToken = json['api_token'];
    code = json['code'];
    createdAt = json['created_at'];
    imageurl = json['imageurl'];
    region = json['region'];
    city = json['city'];
    category = json['category'];
    subCategory = json['sub_category'];
  }


}
